[package]
name = "thorium"
version = "2.0.6"
edition = "2024"
build = "build.rs"

[package.metadata.build]
number = 121
switch = 1

[profile.release]
lto = true

[build-dependencies]
toml_edit = "0.19"
